### ISSUE TITLE
error code 

### ISSUE THREAD

**Issue by Orpheusssl** [antbag-pm-pl/ChatGames#1]
[21:21:19.858] [Server thread/INFO]: Orpheussl joined the game
[21:22:07.089] [Server thread/CRITICAL]: ErrorException: "Undefined property: antbag\chatgames\Main::$rewardEnabled" (EXCEPTION) in "plugins/ChatGames-main/src/antbag/chatgames/Main" at line 54
--- Stack trace ---
  #0 plugins/ChatGames-main/src/antbag/chatgames/Main(54): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[57] Undefined property: antbag\chatgames\Main::$rewardEnabled, string[86] C:\Users\..a..atay\Desktop\tekrar\plugins\ChatGames-main\src\antbag\chatgames\Ma, int 54)
  #1 plugins/ChatGames-main/src/antbag/chatgames/WordTask(14): antbag\chatgames\Main->scrambleWord()
  #2 pmsrc/src/scheduler/TaskHandler(113): antbag\chatgames\WordTask->onRun()
  #3 pmsrc/src/scheduler/TaskScheduler(137): pocketmine\scheduler\TaskHandler->run()
  #4 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 1200)
  #5 pmsrc/src/Server(1782): pocketmine\plugin\PluginManager->tickSchedulers(int 1200)
  #6 pmsrc/src/Server(1671): pocketmine\Server->tick()
  #7 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #8 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#7, string[34] C:\Users\..a..atay\Desktop\tekrar\, string[42] C:\Users\..a..atay\Desktop\tekrar\plugins\)
  #9 pmsrc/src/PocketMine(357): pocketmine\server()

**Comment by antbag-dev** [comment]
Sorry ill fix it ASAP

**Comment by antbag-dev** [comment]
https://poggit.pmmp.io/ci/antbag-dev/ChatGames/ChatGames/dev:23
